# Generated by Django 2.2.1 on 2019-05-24 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ilk_olcum', models.DecimalField(decimal_places=1, max_digits=2)),
                ('son_olcum', models.DecimalField(decimal_places=1, max_digits=2)),
                ('malt_miktari', models.DecimalField(decimal_places=1, max_digits=3)),
                ('hop_miktari', models.IntegerField()),
                ('abv', models.DecimalField(decimal_places=2, max_digits=4)),
                ('kaynatma', models.IntegerField()),
                ('mash_time', models.IntegerField()),
            ],
        ),
    ]
