# Generated by Django 2.2.1 on 2019-05-27 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0002_auto_20190527_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='sure',
            field=models.FloatField(default=4.5),
            preserve_default=False,
        ),
    ]
